# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      package_vsix:
        # Friendly description to be shown in the UI instead of 'name'
        description: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  package_vsix:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.9.1
      with:
        # Set always-auth in npmrc.
        always-auth: false # optional, default is false
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: latest # optional
        # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
        architecture: x64 # optional
        # Set this option if you want the action to check for the latest available version that satisfies the version spec.
        check-latest: true # optional
        # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
        # registry-url:  # optional
        # Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
        # scope: # optional
        # Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
        token: ${{ github.server_url == 'https://github.com' && github.token || '' }} # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
        # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
        cache: npm # optional
        # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
        cache-dependency-path: package-lock.json # optional
        
    - name: Install dependencies
      run: npm install | npm install -g @vscode/vsce
    
    - name: Package Extension
      run: vsce package
